# Generated by Django 6.0.2 on 2026-02-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/images')),
                ('address', models.TextField()),
                ('contact', models.TextField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
